FROM python:3.7-stretch

COPY setup.py Pipfile Pipfile.lock /srv/

WORKDIR /srv

RUN pip install pipenv && pipenv install --system && apt update && apt install -y poppler-utils && useradd -ms /bin/bash gunicorn

COPY ./backend /srv/backend

COPY ./RecordLib /srv/RecordLib


USER gunicorn

EXPOSE 8000

ENTRYPOINT ["/usr/local/bin/gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "--access-logfile", "/srv/backend/backend/wsgi.py"]