# Generated by Django 2.2.9 on 2020-02-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanslate', '0006_sourcerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerecord',
            name='parse_status',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('SUCCESSFULLY_PARSED', 'SUCCESSFULLY_PARSED'), ('PARSE_FAILED', 'PARSE_FAILED')], default='UNKNOWN', max_length=100),
        ),
    ]
