# Generated by Django 2.2.6 on 2019-11-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujs', '0003_auto_20191114_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceRecord',
        ),
    ]
